language: java

sudo: required  #Docker runs as root, permissions are needed

services:
  - docker

env:
  global:
    - secure = "ch0HHa5BxOJXhgucblWzUI1jnKhRTj/fOmgvb0itANRdNdeVUUJo1XH6If8gxm71fiyaEnZPKvzYr71PrxxUKp48GyzX7k/jpCwWSWnUrZev7pvc2kpF2JUkl6WnXAps3wVMCzwoL+oA7cQd9yiBtysBOqPr52xTzBX5rnt8chIK8Q+u/MUCvnDoe7k+KHontbofYKaFd+9khbx7NSQlDBvxDfykGwm/U8vHrYwF0V2zd6OPAB7/l4mETObwi2J0HEwNwg9R+aW+gSzIKpIDJedkgqKDUR6D8IcJo8143FywmDajK2us2s8+I1L21jTmySuQ5ML1plfpBXBIPRXJKzsmhvz4AlwaVI7AONuDHdOruR3UP2T8NO9IcaCLahaBbTcx0NJ6rtm+JFQX8ZAybtGZWJDSSCI0nX+tjhFlHV8CkO54p12LuIQ7gWE2jDnYBRIan1YoKgAQuYC+nlEKNzmJOp6JmwJSp14plKt9S0EVSeRBmhnHMD9PvrmycdqVGIBnAQ4rTzClxPwGp16YMRpHnbOxTRpelYECKOAJf/xrQNLHqIVQokIloEPMCedVJtNOdh5fDXLYaRa7nSfN1hGLE9VRCJsLSyhY0+dkOy9XSO54m9jFI+V9qfoINY8wi3+UVenss5kGci59SuzaoHCVCrcp75wZ3OpvG34ucuA="
    - secure = "qQKvwnz3EGxiUC1FaH8YCWIiaIDZvyJzG3C5hBw8xjrSZJwvd1RiwAoa3i2pujM0auIrOSsUuzs9OdDznoy7upIbX5cSd+j6mzY52CZ5LRKsUCCUmr0p5FrlC7J9cV8darY/Fw7DElHJV1XMQ1YEi070pn/yMIYaF66t7OjZ/bOXQWToNChJ6dO/jDKu+OjMTbEh7SVGV95mw+4i/q1J+FTiJmCHyxRtPz0/txFG9TmcKOU6FnFUM7fHbe0F/iVOc/CouL3B03LKOkDAM8HxedQ1uONHCOjwAf9hU8xg4Egf4EhOZPCnJfDuoUWiskecCFEUEr6aOK3bPHErQz4L02iIB9OaYFTiLVdaYEKPgfU1WF+oIalEcAASURK0oK9ThUdccR2xR/Uf4tgghMHo3kKx+pubPCE0SttYmVGeUXZ+3OLQAKf2u+nvxv4eTuFa5fbFYqYwHXFqSPZBGiJI7aBN/DGuAo8hJ7Tx/8LjLiuIbnZa9i9F20P9Pixk53ogF9HHhksIh095Dx0yBtbhuAJztP87f7KB6bXjqO+F7ddCqwcGU1ACcMUwlBQ+HQZk6/Rf6kEa6WognuSk5AQftlbrx558y7A1KPSHO/mHy6krszQUzxYoAq3jBfedv6sSDyMATtpn4JZcOEgidqLboYBOpNMnlnPQ8lTx+jT8OQY="  

before_install:
  - chmod +x ./mvnw 

script:
  - ./mvnw clean install
  - docker build -t tacs-grupo3-back_end .

after_success:
  - docker login -u $USERDOCKER -p $PASSWORDDOCKER
  - docker tag tacs-grupo3-back_end $USERDOCKER/tacs-grupo3-back_end:$TRAVIS_BUILD_NUMBER
  - docker push $USERDOCKER/tacs-grupo3-back_end:$TRAVIS_BUILD_NUMBER
  - docker tag tacs-grupo3-back_end $USERDOCKER/tacs-grupo3-back_end:latest
  - docker push $USERDOCKER/tacs-grupo3-back_end:latest