language: java

sudo: required  #Docker runs as root, permissions are needed

services:
  - docker

env:
  global:
    - secure = "Fp7wbEiO23UxL020IZbA64XPHAVxdTiFTB7nhESHRR7u14gAOu+8XPbAyYah18kPkBZHQUQViyI9jTOYbv/QdLTvvIOccPxWX2o0rW9ZG/pLB/ifz2zkwTrz5pnnrkyPSheMOVoxbb2fsjeSmm6Nw7A5DHolzpmLLITdHSEXTdyeF3+j3CbNAGqfPgIDNSVRGmCBBART2iVi8iewbvNb63SCZXMg5FOMeFxl9vM6lxAU7o+vsK7XLPxeAw9NjvuY770rXdGHVPMObPfVd/bmlLQvnK0+d0xVFis8berXOe1/j5M4z0Q1nHMdtuodflRm/SEZlbpwzH1NsH3HVds2hw1E++1it5KNs+KVSGvdGUB0755uI6350lovU4q9jVk7Bf64FsDD0kks57bJI0V+U4KcFGvxnK2DT7V1Duji0UzOv8LqyM3tHHv9bq87OqPxRKSGKqGCvHgBovyA1hVk7wdHdxgvDjAqj659e+Qz279YmywMnbYDYv8Ua/oaj/o8MBkeZPTicZBeq7cn6fyMZ2wec8z+PiEhZL0o9PoWv0DW/m+1OI7yML0EqlFt01uFvhCwTmoToH+hSbhcRiewLzUF1iqB/6ilb9Bw2GAUsQnUYb1pX283FapSynkE6Dw1pTFcqPGIQo78Oe3bMnPsBuQgKS62AE0ESbN8MZpkK20="
    - secure = "WbGMWUViKbRsE/a07Sw6mJ21lLBsAxvo8jwIzD4gmStRwlMBrfRNVOFgOxnIzb1R/BMcJK8oCBh6yYYXXyL/SOpOr2KNkr6SvRxcHxTySqSeoP7yp0nOSMgDEQhPtje4HF+TRA819OcFM/aTE3N1IYZlMfSI4uW2Vmv5aXjMhXxOenwjmKsxC0pmWrc4sTjnUm9xyoqmrEvCItRXenPeVCwS3xVI5t2ZCRFn0MyQshk8E09Ub+glRpvp7C2CbGMg31ksjwy9iQtSFcSIciACkvaAkSR3E98xS01q0e5sSyugxZUDeJdHpDJbcK0++1Sx51T/AgxBpop4z1Kx7dk5J6xGXXRVv2DNwcKlcgpcqiYsY8u9q1RY2DlqvtiaZb5XMoZ9lz3IBg3wDTbe8mr6cT3/NiPz/s45cF9u73XHtEJ7+LIuqRJ+Gy280UJnBZkWM3e29RcCED01MVFqdBOERxlodySml7n59WT8HuSRjYQAFwncUoGxSRPsi//kvvFmZu0NAx6YMtp/0H+itbwaTDqS3axZqsYwKWbVrtETsLztUv1Ho5oVHMySIZ3bzfZmKCBpC+XBQOvXR8qC0kuVSsP70nK6jfsJbyaDIr98OCrFafquCQqM770yZfsDUKCCUaqrb5bgB1NYTidw8vgdevCz0NTrc8k/USBNk/RjyMQ="  

before_install:
  - chmod +x ./mvnw 

script:
  - ./mvnw clean install
  - docker build -t tacs-grupo3-back_end .

after_success:
  - docker login -u $USERDOCKER -p $PASSWORDDOCKER
  - docker tag tacs-grupo3-back_end $USERDOCKER/tacs-grupo3-back_end:$TRAVIS_BUILD_NUMBER
  - docker push $USERDOCKER/tacs-grupo3-back_end:$TRAVIS_BUILD_NUMBER
  - docker tag tacs-grupo3-back_end $USERDOCKER/tacs-grupo3-back_end:latest
  - docker push $USERDOCKER/tacs-grupo3-back_end:latest