language: java

sudo: required  #Docker runs as root, permissions are needed

services:
  - docker

before_install:
  - chmod +x ./mvnw 

script:
  - ./mvnw clean install
  - docker build -t tacs-grupo3 .

 after_success:
  - docker login -u $USERDOCKER -p $PASSWORDDOCKER
  - docker tag tacs-grupo3 $DOCKER_USER/tacs-grupo3:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/tacs-grupo3:$TRAVIS_BUILD_NUMBER
  - docker tag tacs-grupo3 $DOCKER_USER/tacs-grupo3:latest
  - docker push $DOCKER_USER/tacs-grupo3:latest