language: java

sudo: required  #Docker runs as root, permissions are needed

services:
  - docker

env:
  global:
    - secure = "BquBunZZfw4+8Qe3bTeq8toNG5O0giWs3NaTga5e+5d+b+K2841l+a+94CCodfo5kPpNsHIAf+wjkjfjuMNp/DphkEqkeA3vFqiTKjpfy4BfZeeygqjYi9CK3GKUDlZkwpFX3n5SNrsWjXD0g+GMeMpe9w8jGgsGHFGZVEMZYTTpB+IZveB+DLrK8tWXDFXy8UfJn1JwwKUbmJfFYyP4pIBhREvze/J1OObaE2hkV51LZGEi4EkU3b6eqjp6bR6orSxlLFy2IDh9PiYN8o1wHfjPxFsze/cDBNfjsV4VZr3dRz3rjppurLa1zXmOyef5b+qr5LlRXvhjeftKf2FjsvtLho1jLsd2/6OL/slofy4bTXZ446GJxX3PgFgq0UkVAQdAf3745uwTX6X4oI5+8kFrhDn37kVVp3Ge7Q/bYhpG/1u/Q2IFDYd1OVGewIl1Yuoe8jK78bzXZrSGGpp54/FAVBkk0Uh7gRqhqsrzDAn0Dd3glTaI/zrmttZVrDkYE+6+5g5J4L0e6LDf1tw/XM61Cg+0Lr4WTeNSaKXu52rNorHW/MWeOAJJvHKXUGSRF+jBMzLe9wnjPXbDbPkOBmefqbk+g0PumKhARhg9BlCnJ1FnSYngJWQzW5Ca4fxNkWlWxrHxLmr4+icPOkd9bAdDeoRleUtkc6r9w/AwBn8="
    - secure = "KtzANNNdSn5wuHCXdXyHEaNPbuEa///qLjapfvEZms10bYYXjPXbX1bzPsCGJ89i4YQR+kynbAfwYfeRvuFdJdghy6Vd1Kn7nSDFlt9q51OSkfnPrzootc9LhT2bzrtW14F245kydE2kwEADyQbSUC+JSobX0tXZnN9vBTv9t/bohmnlsrM/eZOoK5Qx7Q5M4koXB82k/1Pr9Me6ZqMkYX6WFG5XGL7J4v7DDkYkLXl/la3R3ApTEEvszlMv5Bpds5zuYdUhbDVsfF8l1sUsOoBYiBMPmnEoCq2l9MyihhkiXwAI/l1FTJ07X/EGVlN5wRWQzokfpBbWbiSidpYKUbNKOfBpzFrcpxQl6k0bKrTaNT3/AEw+UWCghDsUkme9OyUW7qxBvB4i4/J2A8KgaDkspAq/8Y1rDnn70sxx6yf5uE1Xq2wC8IzO9U7P7tsuEOlmCl2snrxkopt8byyIKJT+CX00WVi++tUa/jkOyQs7enWNSZnBMFOh/p0+ifOYJ34los/uFXim8xJi1ScbuSHAHpSAS6+G91JnISvomXbjMTbXPs8mjtwPRcna7PWZ6Jx1mTfThxBEhCbnfPAK0WbsfFjCADSJC/JpDo+xEdGL9E5W9pYWGhTcBrTvPX3KvUbLXO3LyJsxxDj6zGl2Uj1LM+54m+ygPrlFjXvZmsA="  

before_install:
  - chmod +x ./mvnw 

script:
  - ./mvnw clean install
  - docker build -t tacs-grupo3-back_end .

after_success:
  - docker login -u $USERDOCKER -p $PASSWORDDOCKER
  - docker tag tacs-grupo3-back_end $USERDOCKER/tacs-grupo3-back_end:$TRAVIS_BUILD_NUMBER
  - docker push $USERDOCKER/tacs-grupo3-back_end:$TRAVIS_BUILD_NUMBER
  - docker tag tacs-grupo3-back_end $USERDOCKER/tacs-grupo3-back_end:latest
  - docker push $USERDOCKER/tacs-grupo3-back_end:latest